config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # This means when we receive a get request with / url we invoke the index action within the HomeController
  # get "/" => 'home#index', as: :home
  root 'home#index'

  get "/contact" => 'home#contact' #rails auto generate a url helper called contact_path and (contact_url)

  post "/contact_submit" => 'home#contact_submit'

  get "/faq" => 'home#faq'

  # get "/questions/new" => 'questions#new', as: :new_question
  #
  # post "/questions" => 'questions#create', as: :questions
  #
  # get "/questions/:id" => 'questions#show', as: :question
  #
  # get "/questions" => 'questions#index'
  #
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  #
  # patch '/questions/:id' => 'questions#update'
  #
  # delete 'questions/:id' => 'questions#destroy'

  # the url helpers (when we set it using `as`) is only concerned about the
 # URL and not the VERB. So even if we have two routes with the same url
 # and different verbs, the url helper should be the same. and they will automatically know which request to take, the form one or the get one.
 resources :users, only: [:new, :create] do
   resources :likes, only: [:index]
 end
 resources :sessions, only: [:new, :create] do
   delete :destroy, on: :collection
 end

  resources :questions, shallow: true do
    # When we define a route within the block for `resources` we make the route
   # associated with the questions controller. We have different options we
   # can use with these routes:
   # on: :collection => this makes the route not include an :id or :question_id
   # in it. This is very similar to the `index` action url
   # get	'/questions/search' => 'questions#search', as: :search_questions
    get :search, on: :collection

    # on: :member => this makes the route include an `:id` this is usually
    # useful for routes on actions that are related to a given record. This is somewhat similar to the edit action.
    # get '/questions/:id/flag' => 'question#flag', as: :flag_question
    get :flag, on: :member

    # if you dont include any option (neither collection nor member) then youre defining a nested resources which means it will include ':question_id' in the URL
    # POST	'/questions/:question_id/approve' => 'questions#approve', as: :question_approve
    post :approve

    # nesting the answers resources whithin the questions resources block will make it so that every 'answers' route is prefixed with: '/questions/:question_id'. We will need the `question_id` to create an answer associated with a question so we will stick with this way of defining the routes.
    resources :answers, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user

  # this sets up the one to many association from the question model. you always provide plural from the model, in this case 'answers'
  # this will give us handy methods to easily work with the association
  # thi must provude a 'dependent' option to your has_many
  # you can put :destroy if you'd like to delete all the answers associated with a question when the question gets deleted.
  # you can also put ':nullify' which will update all the asssociated answers to have a question_id of null when the question is deleted
  has_many :answers, lambda { order(created_at: :desc)}, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, uniqueness: {case_sensitive: false, message: "Must be unique"}
  # with scope we validate that the combination of two fields is unique. In the
  # example below, we're validating that the combination of title/body is unique
  validates :body, length: { minimum: 5 },
                uniqueness: { scope: :title }

  validates(:view_count, { numericality: { greater_than_or_equal_to: 0 } })

  validate :no_monkey

  after_initialize :set_defaults
  before_validation :titleize_title


  def user_full_name
    if user
      user.full_name
    else
      'Annonimous'
    end
  end

  def like_for(user)
    likes.find_by(user: user)
  end

   # scope :recent_ten, lambda { limit(10).order(created_at: :desc) }

   def vote_value
     votes.up.count - votes.down.count
   end

  private

  def no_monkey
    if title && title.include?('monkey')
      errors.add(:title, 'No monkeys please!')
    end
  end

  def set_defaults
    self.view_count ||= 0
  end

  def titleize_title
    self.title = title.titleize
  end


end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController

  def index
    # render "home/index"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # the before ation method here registrer a method usually private to be executed just before controller actions. This happens within the same request/response cycle which means if you define an instance variable it will be available within the action
  # You can optionally give options: "only" or "except" to restrict the actions that 'before_action' method applies to.

  before_action :authenticate_user, except: [:index, :show]
  before_action :find_question, only: [:edit, :update, :destroy, :show]
  #the before_action method will be executed at order that the they get defined with. This means the authenticate_user will be called before the authorize_access method. This means that the user will be inside authenticated when we're inside the authenticate_user method so we dont have o check for that.
  before_action :authorize_access, only: [:edit, :update, :destroy]

  # This action is to show the form for creating a new question
  # the URL: /questions/new
  # the path helper will be: new_question_path
  def new
    @question = Question.new
  end

  # this action is to handle creating a new question after submitting the form
  # that was shown in the new action
  def create
    @question = Question.new question_params
    @question.user = current_user
     if @question.save
       flash[:notice] = 'Question Created!'
       redirect_to question_path(@question)
     else
       flash.now[:alert] = 'Please see errors below'
       render :new
     end
  end

  # this action is to show information about a specific question
    # URL: /questions/:id (for example /questions/123)
    # METHOD: GET
  def show
    @answer = Answer.new
    @like = @question.like_for(current_user)
  end

  # this action is to show a listings of all the questions
   # URL: /questions
   # METHOD: GET
  def index
    @questions = Question.order(created_at: :desc)
  end

  # this action is to show a form pre-populated with the question's data
# URL: /questions/:id/edit
# METHOD: GET
  def edit
  end

  # this action is to capture the parameters from the form submission form the
  # edit action in order to update a question
  # URL: /questions/:id
  # Method: path
  def update
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question Deleted'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def find_question
    @question = Question.find params[:id]
  end

  def authorize_access
    unless can? :manage, @question
      # unless (current_user == @question.user || current_user.admin?)
      # head :unauthorized # this will send a 401 response
      redirect_to root_path, alert: 'Access Denied'
  end
end


end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= @question.errors.full_messages.join(", ")%>
<!-- if the object you pass to the form is persisted (has an ID in the DB)  then rails will automatically make the form submit a patch request with URL in this question question_path(@question) (same as a show link with PATCH) @question variable is persisted in this case so it will have a title and a body so those will be pre-populated in their respective fields-->

<%= form_for  @question do |f| %>

<%# We use form_for when we're creating a form related to a Rails model. the first argument of the form_for must be an ActiveRecord object. if the first argument is a new instance of the ActiveRecord class, for instance,
Question.new then the form will automatically send a post request to the standard create action url which is in this case: question_path%>

  <div class="form-group">
    <%# we can use f.label and f.text_field to generate a label/text input group in this case `title` must be an attribute for the variable you pass to form_for which is @question in this case. The label will have a `for` attribute that matches the id of the generated input field for the title. The title input field will have a name attribute that is model_type[field] In the example below the `name` attribute for the input field will be: question[title] The input field will be populated with a value if @quation has that attribute value set to something%>
    <%=f.label :title %>
    <%=f.text_field :title %>
  </div>
  <div class="form-group">
    <%=f.label :body %>
    <%=f.text_area :body %>
  </div>
  <div>
    <%= f.collection_select(
    :tag_ids, Tag.all, :id, :name, {},
    { multiple: true, class: 'chosen-select'}
    ) %>
  </div>
  <br>
  <br>
  <%# this will automatically generate a submit button. The label for the button will depend on the `@question` variable. If @question is a new instance then the label of the button will be `Create #{model name capitalized}`. If you're not happy with the label, you can pass the label as a first arguement: f.submit 'Create'  %>
  <%= f.submit btn_label %>
<% end %>

<script>
$('.chosen-select').chosen({width: '300px'});
</script>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>



<!-- This line will look for partial named conventionally '_form.html.erb'  within the same folder as this file which is: /app/views/questions/.-->
<!-- Partials will have access to the same instance variable as a template they are rendered within. In this case the `_form` partial will have access to -->
<!-- @question variable. If you want to pass a local varialbe, then you will have to do that explicitly in this case there will be a local variable named btn_label within the _form partial and it will have the value of "Update" -->


<%= render 'form', {btn_label: 'Update'}  %>

<!-- <%#= render '/question/form' %> -->

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |q|%>
  <h2><%=link_to q.title, question_path(q) %></h2>
  <hr>
<%end%>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', {btn_label: 'Submit'} %>

app/views/questions/show.html.erb
<div class="container">
<h1><%= @question.title %></h1>

<!-- <%#= question_answers_path(@question)%> -->

<p><%= @question.body %></p>

<p>Created by: <%= @question.user_full_name %></p>

<% if can? :manage, @question %>
  <%= link_to "Edit", edit_question_path(@question)%>
  <%= link_to "Delete", question_path(@question),
                        method: :delete,
                        data: {confirm: 'Are you sure you want to delete this question?'}%>
<%end%>
<% if user_signed_in? && can?(:like, @question)%>
  <% if @like.present? %>
    <%= link_to "Unlike", like_path(@like), method: :delete %>
    <%else%>
  <%= link_to "Like", question_likes_path(@question), method: :post %>
  <%end%>

<%end%>
<%= pluralize(@question.likes.count, "Like") %>
<br>
<br>

<section class="vote-widget">
  <%= upvote_link(@question)%>
  <%= downvote_link(@question)%>
  <%= @question.vote_value %>
</section>

<section>
  <%= @question.tags.map(&:name).join(", ") %>
</section>
<%#=  form_for @answer, url: question_answers_path(@question) do |f| %>
<h2>Create Answer</h2>

<%= @answer.errors.full_messages.join(', ')%>
<%= form_for [@question, @answer] do |f| %>
<div class="form-group">
  <%= f.label :body%>
  <%= f.text_area :body%>
</div>
<br>
<div class="form-group">
<%= f.submit%>
</div>
<% end %>
<br>
<% @question.answers.each do |answer| %>
  <% if answer.body != nil %>
  <h2>Answers</h2>
  <%end%>
<%= answer.body %>
<% if (can? :manage, @question) || (can? :delete, answer) %>
  <%= link_to 'delete', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?'} %>
<%end%>
<hr>
<%end%>
</div>