Blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "home#index", as: :home

  get "/about" => "home#about"

  resources :users, only: [:new, :create, :edit, :update]
  resources :passwords, only: [:edit, :update] 
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :comments
  end


end

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    nav {
      float: right;
      padding: 10px;
      background-color: lightblue;
      width: 100%;
    }
    #nav-bar {
      float: right;
    }
    </style>
    </head>

    <body>
    <nav>
      <div id="nav-bar">

        <%= link_to 'Home', home_path %>
        |
        <%= link_to 'About', about_path %>
        |
        <%= link_to 'New Posts', new_post_path %>
        |
        <%= link_to 'All Posts', posts_path %>
        |
        <% if user_signed_in? %>
          Hello <%= link_to current_user.first_name.titleize, edit_user_path(current_user) %>
          <%= link_to 'Sign Out', sessions_path, method: :delete%>
          |
          <%= link_to 'Update Your Password', edit_password_path(current_user) %>
        <% else %>
          <%= link_to 'Sign up', new_user_path %>
          |
          <%= link_to 'Sign in', new_session_path %>
        <%end%>
      </div>
    </nav>
    <br>
    <br>
    <hr>
    <%= notice || alert %>
    <%= yield %>
  </body>
</html>