PM_Tool/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/" => "home#index", as: :home

  get "/about" => "home#about"

  resources :projects do
    get :search, on: :collection
    get :flag, on: :member
    post :approve
    resources :discussions  do
      get :search, on: :collection
      get :flag, on: :member
      post :approve
      resources :comments
    end
    resources :tasks do
        patch '/tasks/:id/status' => 'tasks#status', as: :status
    end
  end

end

PM_Tool/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :discussion
end

PM_Tool/app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :project
  has_many :comments, dependent: :destroy
end

PM_Tool/app/models/project.rb
class Project < ApplicationRecord
  has_many :discussions, dependent: :destroy
  has_many :tasks, dependent: :destroy
  validates :title, presence: true, uniqueness: true

  validate :valid_deadline

  def valid_deadline
    if self.due_date < Date.today
      errors.add(:due_date, "is invalid.")
    end
  end



end

PM_Tool/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  before_validation :set_default

  private

  def set_default
    self.status ||= false
  end
end

PM_Tool/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

PM_Tool/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:discussion_id]
    comment_params = params.require(:comment).permit(:body)
    @comment = Comment.new comment_params
    @comment.discussion = @discussion
    if @comment.save
      redirect_to project_discussion_path(@project, @discussion), notice: 'Comment Created!'
    else
      render 'discussions/show'
    end
  end

  def edit
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:discussion_id]
    @comment = Comment.find params[:id]
  end

  def update
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:discussion_id]
    @comment = Comment.find params[:id]
    comment_params = params.require(:comment).permit(:body)
    if @comment.update(comment_params)
      redirect_to project_discussion_path(@project, @discussion)
    else
      render :edit
    end
  end


  def destroy
    project = Project.find params[:project_id]
    discussion = Discussion.find params[:discussion_id]
    comment = Comment.find params[:id]
    comment.destroy

    redirect_to project_discussion_path(project, discussion), notice: "Comment deleted!"
  end
end

PM_Tool/app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def create
    @project = Project.find params[:project_id]
    discussion_params = params.require(:discussion).permit(:title, :body)
    @discussion = Discussion.new discussion_params
    @discussion.project = @project
    if @discussion.save
      redirect_to project_path(@project), notice: 'Discussion created!'
      @comment = Comment.new
    else
      render 'projects/show'
    end
  end

  def show
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
    @comment = Comment.new
  end

  def edit
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
  end

  def update
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
    discussion_params = params.require(:discussion).permit(:title, :body)
    if @discussion.update(discussion_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    project = Project.find params[:project_id]
    discussion = Discussion.find params[:id]
    discussion.destroy
    redirect_to project_path(project), notice: 'Discussion Deleted!'
  end
end

PM_Tool/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

end

PM_Tool/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    project_params = params.require(:project).permit([:title, :description, :due_date])
    @project = Project.new project_params
     if @project.save
       redirect_to project_path(@project)
     else
       render :new
     end
  end

  def show
    @project = Project.find params[:id]
    @discussion = Discussion.new
    @task = Task.new
  end

  def index
    @projects = Project.order(title: :desc)
  end

  def edit
    @project = Project.find params[:id]
  end

  def update

    @project = Project.find params[:id]
    project_params = params.require(:project).permit(:title, :description)
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find params[:id]
    @project.destroy
    redirect_to projects_path
  end
end

PM_Tool/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @project = Project.find params[:project_id]
    task_params = params.require(:task).permit([:title, :body, :due_date])
    @task = Task.new task_params
    @task.project = @project
     if @task.save
       redirect_to project_path(@project)
     else
       render 'projects/show'
     end
  end

  def edit
    @project = Project.find params[:project_id]
    @task = Task.find params[:id]
  end

  def update
    @project = Project.find params[:project_id]
    @task = Task.find params[:id]
    task_params = params.require(:discussion).permit(:title, :body, :due_date)
    if @task.update task_params
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    project = Project.find params[:project_id]
    task = Task.find params[:id]
    task.destroy
    redirect_to project_path(project)
  end

  def status
    project = Project.find params[:project_id]
    task = Task.find params[:task_id]
    if task.status == false
      task.update_attribute(:status, "Done")
    else
      task.update_attribute(:status, false)
    end
    redirect_to project_path(project)
  end
end

PM_Tool/app/helpers/application_helper.rb
module ApplicationHelper
end

PM_Tool/app/helpers/comments_helper.rb
module CommentsHelper
end

PM_Tool/app/helpers/discussions_helper.rb
module DiscussionsHelper
end

PM_Tool/app/helpers/projects_helper.rb
module ProjectsHelper
end

PM_Tool/app/helpers/tasks_helper.rb
module TasksHelper
end

PM_Tool/app/views/comments/edit.html.erb
    <%= @comment.errors.full_messages.join(', ')%>
    <%= form_for [@project, @discussion, @comment] do |f| %>
      <div>
        <%= f.label :body%>
        <%= f.text_area :body%>
      </div>
      <br>
      <div>
      <%= f.submit%>
      </div>
    <% end %>

PM_Tool/app/views/home/about.html.erb
<h1>About me</h1>

<%= image_tag('https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/1383591_521982757889328_72248226_n.jpg?oh=cebec813005a8174e65000f1e4c64cf0&oe=5867744C', width: 150, height: 150) %>

<p>Thaisa de Carvalho Marinho</p>

PM_Tool/app/views/home/index.html.erb
<h1>Welcome to my Project Management Tool!</h1>

PM_Tool/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PM Tool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    nav {
      float: right;
      padding: 10px;
      background-color: lightblue;
      width: 100%;
    }
    #nav-bar {
      float: right;
    }
    </style>
    </head>

    <body>
    <nav>
      <div id="nav-bar">

        <%= link_to 'Home', home_path %>
        |
        <%= link_to 'About', about_path %>
        |
        <%= link_to 'New Project', new_project_path %>
        |
        <%= link_to 'All Projects', projects_path %>
      </div>
    </nav>
    <br>
    <br>
    <hr>
    <%= yield %>
  </body>
</html>

PM_Tool/app/views/tasks/edit.html.erb
<%= @task.errors.full_messages.join(', ')%>
<%= form_for [@project, @task] do |f| %>
  <div>
    <%= f.label :title%>
    <%= f.text_field :title%>
  </div>
  <br>
  <div>
    <%= f.label :body%>
    <%= f.text_area :body%>
  </div>
  <div>
    <%= f.label :due_date%>
    <%= f.date_field :due_date%>
  </div>
  <br>
  <div>
  <%= f.submit%>
  </div>
<% end %>